### ISSUE TITLE
DOB Issue on CVS

### ISSUE THREAD

**Issue by DavidJamesAustin** [SteveCaruso/covid-filler-nj#3]
Following the format of dummy data, CVS errors out if I don't manually click into the DOB field.

![Screen Shot 2021-03-28 at 12 20 01 AM](https://user-images.githubusercontent.com/29986018/112742291-5bceaf80-8f5b-11eb-8e7b-b8b26d92e50a.png)

**Comment by SteveCaruso** [comment]
(To your prior comment before the edit, I'm going to be adding a section to the README.md file about how the TSV data is structured along with all of the expected values – some of which are expected to change with the expanded NJ eligibility requirements dropping soon. In a future version, I want to put together a bookmarklet generator which will allow folks to choose the order of the columns and the delimiter arbitrarily to fit whatever spreadsheet they're using.)

**Comment by DavidJamesAustin** [comment]
> (To your prior comment before the edit, I'm going to be adding a section to the README.md file about how the TSV data is structured along with all of the expected values – some of which are expected to change with the expanded NJ eligibility requirements dropping soon. In a future version, I want to put together a bookmarklet generator which will allow folks to choose the order of the columns and the delimiter arbitrarily to fit whatever spreadsheet they're using.)

Awesome. Appreciate the responsiveness! I figured it was just me being quick to jump at an issue -- and then I discovered the DOB issue. Seems to easily be managed with a manual click!

**Comment by SteveCaruso** [comment]
No problem. :-)

I found that they _just_ updated the form this evening, so if it needs a click and then validates fine, then I need to check to see if they changed which EventListener is handling validation.

**Comment by DavidJamesAustin** [comment]
Amazing. Good spot! I work with a group of 150+ volunteers (vaccinefairy.org - if you want to peek!) and I wanted to test this out before rolling out the info to the whole team.

**Comment by SteveCaruso** [comment]
Your group looks awesome! :-)

I believe I just fixed the validation error. If you could check to see if it works I'd appreciate it and I'll close this bug out if that did the trick.

In the meantime, I'm going to put together an explanation of the TSV data, and start work on the custom bookmarklet generator to set the columns in arbitrary order.

**Comment by DavidJamesAustin** [comment]
Same error for me! :( I also noticed it went to the wrong "sex assigned at birth"

**Comment by SteveCaruso** [comment]
Curious. I can't seem to reproduce it. Which browser are you using?

**Comment by SteveCaruso** [comment]
(I've also just updated the [README.md](https://github.com/SteveCaruso/covid-filler-nj/blob/main/README.md) with more information about the spreadsheet column order, etc.)

**Comment by DavidJamesAustin** [comment]
Chrome - latest public version. Not quite sure what's going on there! I also re-added the bookmarklet to see if that would solve it.

**Comment by DavidJamesAustin** [comment]
Attempted in incognito. Issue persists with invalid DOB + sex selection.

**Comment by SteveCaruso** [comment]
Grr, frustrating. I'm running the same version of Chrome and I still can't seem to reproduce the problem on my system.

Is the Console throwing any errors pertaining to index.js?

Could also possibly be trying to move forward too fast. I'm going to try and add a small pause before it submits.

**Comment by DavidJamesAustin** [comment]
I didn't see anything in the console - I will try again with tonight's drop with the updates you've made and report back! :)

**Comment by DavidJamesAustin** [comment]
The issue still stands! :(

**Comment by SteveCaruso** [comment]
Sorry, I didn't get to work on it last night. Blast. :-(

I'm going to try and put together a different strategy this afternoon and implement it.

**Comment by DavidJamesAustin** [comment]
Appreciate it! This awesome tool is very close to perfection for CVS + RiteAid. Let me know once you have somethin' new and I'd be happy to give it a run.

**Comment by SteveCaruso** [comment]
I think I finally nicked this problem, but forgot to close the thread.

If it still rears its head, please re-open another report, but in the meantime be sure to check out the new custom bookmarklet generator for other forms.
